use std::collections::HashMap;
use std::path::PathBuf;

use tower_lsp::lsp_types::*;

use crate::config::WikiConfig;
use crate::hooks::apply::apply_hook_result;
use crate::hooks::lua::{build_hook_note_input, HookRunner};
use crate::parser;

/// Default hooks embedded at compile time.
const DEFAULT_CHECKLIST_HOOK: &str = include_str!("../../examples/hooks/checklist.lua");
const DEFAULT_RELATION_HOOK: &str = include_str!("../../examples/hooks/relation_status.lua");

#[allow(dead_code)]
/// Apply a list of byte-range edits to `content`.
///
/// Each edit is `(start_byte, end_byte, replacement_text)`.
/// Edits must be non-overlapping. They are applied from last to first so byte
/// offsets remain valid throughout.
///
/// Returns `Err` if any edit is invalid (out of bounds, inverted range, or overlap).
pub fn apply_byte_edits(content: &str, edits: &[(usize, usize, String)]) -> anyhow::Result<String> {
    let len = content.len();
    for (start, end, _) in edits {
        anyhow::ensure!(start <= end, "edit has start ({start}) > end ({end})");
        anyhow::ensure!(*end <= len, "edit end ({end}) out of bounds (len={len})");
    }
    // Sort by start ascending, check no overlaps
    let mut sorted: Vec<&(usize, usize, String)> = edits.iter().collect();
    sorted.sort_by_key(|(s, _, _)| *s);
    for w in sorted.windows(2) {
        anyhow::ensure!(
            w[0].1 <= w[1].0,
            "edits overlap: [{}, {}) and [{}, {})",
            w[0].0,
            w[0].1,
            w[1].0,
            w[1].1
        );
    }
    // Apply in reverse order so earlier byte offsets remain valid
    let mut result = content.to_string();
    for (start, end, text) in sorted.iter().rev() {
        result.replace_range(start..end, text);
    }
    Ok(result)
}

/// Render a `toml::Value` as an inline TOML literal (no newlines).
/// Used by `apply_metadata_patch` for targeted in-place key replacement.
fn toml_value_inline(value: &toml::Value) -> anyhow::Result<String> {
    match value {
        toml::Value::String(s) => {
            let escaped = s.replace('\\', "\\\\").replace('"', "\\\"");
            Ok(format!("\"{escaped}\""))
        }
        toml::Value::Integer(n) => Ok(n.to_string()),
        toml::Value::Float(f) => Ok(f.to_string()),
        toml::Value::Boolean(b) => Ok(b.to_string()),
        toml::Value::Array(arr) => {
            let items: Vec<String> = arr
                .iter()
                .map(toml_value_inline)
                .collect::<anyhow::Result<_>>()?;
            Ok(format!("[{}]", items.join(", ")))
        }
        _ => anyhow::bail!("nested TOML tables are not supported in a metadata patch"),
    }
}

/// Apply a metadata patch to a TOML-format note using targeted in-place replacement.
///
/// For each `(key, value)` in `patch`, finds the key's line within the TOML block
/// and replaces only that line — preserving key order, indentation, and all other lines.
///
/// Handles two TOML representations of dotted keys (both are generated by `zk-lsp new`):
/// - Dotted notation: `user.verified = "false"`
/// - Section notation: `[user]` followed by `verified = "false"` on a later line
///
/// Returns `Err` if the note has no TOML metadata block or a key is not found in the block.
pub fn apply_metadata_patch(
    content: &str,
    patch: &HashMap<String, toml::Value>,
) -> anyhow::Result<String> {
    let block = parser::find_toml_metadata_block(content)
        .ok_or_else(|| anyhow::anyhow!("no TOML metadata block found"))?;

    let lines: Vec<&str> = content.lines().collect();
    let trailing_newline = content.ends_with('\n');
    let mut result_lines: Vec<String> = lines.iter().map(|l| l.to_string()).collect();

    'patch: for (key, value) in patch {
        let val_str = toml_value_inline(value)?;

        // Pass 1: dotted-key notation — `user.verified = "false"`
        for i in block.start_line..=block.end_line {
            let line = lines[i];
            let trimmed = line.trim_start();
            if trimmed.starts_with(&format!("{key} =")) || trimmed.starts_with(&format!("{key}=")) {
                let indent_len = line.len() - trimmed.len();
                result_lines[i] = format!("{}{key} = {val_str}", " ".repeat(indent_len));
                continue 'patch;
            }
        }

        // Pass 2: section-header notation — `[table]` … `field = value`
        // Applies when key contains exactly one dot, e.g. "user.verified".
        if let Some(dot_pos) = key.find('.') {
            let table_name = &key[..dot_pos];
            let field_name = &key[dot_pos + 1..];
            // Only handle single-level nesting (no further dots in field_name).
            if !field_name.contains('.') {
                let section_header = format!("[{table_name}]");
                let mut in_section = false;
                for i in block.start_line..=block.end_line {
                    let line = lines[i];
                    let trimmed = line.trim_start();
                    if trimmed == section_header {
                        in_section = true;
                        continue;
                    }
                    if in_section {
                        // Another section header ends this one.
                        if trimmed.starts_with('[') {
                            break;
                        }
                        if trimmed.starts_with(&format!("{field_name} ="))
                            || trimmed.starts_with(&format!("{field_name}="))
                        {
                            let indent_len = line.len() - trimmed.len();
                            result_lines[i] =
                                format!("{}{field_name} = {val_str}", " ".repeat(indent_len));
                            continue 'patch;
                        }
                    }
                }
            }
        }

        anyhow::bail!("key '{key}' not found in TOML metadata block");
    }

    let mut out = result_lines.join("\n");
    if trailing_newline {
        out.push('\n');
    }
    Ok(out)
}

/// Format `content` by running hooks in sequence:
/// 1. Built-in default hooks (checklist.lua + relation_status.lua, embedded at compile time),
///    unless `config.zk_config.disable_default_hooks` is true.
/// 2. User-configured file hooks from `config.zk_config.hooks`, loaded at runtime.
///
/// Cross-file ref-checkbox sync (`@ID` items) is intentionally NOT performed here;
/// that is the exclusive responsibility of the `reconcile` command.
///
/// On any hook error the step is skipped and a warning is emitted; the original
/// content (or the output of the previous step) is passed through unchanged.
pub async fn format_content(content: &str, config: &WikiConfig) -> String {
    let zk = &config.zk_config;
    let mut current = content.to_string();
    if !zk.disable_default_hooks {
        current = run_default_hooks(&current);
    }
    current = run_hooks(&current, &zk.hooks);
    current
}

/// Run the built-in embedded hooks (checklist.lua + relation_status.lua).
pub(crate) fn run_default_hooks(content: &str) -> String {
    let hooks: &[(&str, &str)] = &[
        ("checklist", DEFAULT_CHECKLIST_HOOK),
        ("relation_status", DEFAULT_RELATION_HOOK),
    ];
    let mut current = content.to_string();
    for (name, src) in hooks {
        let runner = match HookRunner::load_str(src) {
            Ok(r) => r,
            Err(e) => {
                tracing::warn!("default hook '{name}' load error: {e}");
                continue;
            }
        };
        let input = build_hook_note_input(&current);
        let result = match runner.run(&input) {
            Ok(r) => r,
            Err(e) => {
                tracing::warn!("default hook '{name}' run error: {e}");
                continue;
            }
        };
        match apply_hook_result(&result, &current) {
            Ok(out) => current = out,
            Err(e) => tracing::warn!("default hook '{name}' apply error: {e}"),
        }
    }
    current
}

/// Run user-configured file hooks loaded at runtime. No-op if `hook_paths` is empty.
pub(crate) fn run_hooks(content: &str, hook_paths: &[PathBuf]) -> String {
    let mut current = content.to_string();
    for path in hook_paths {
        let name = path
            .file_name()
            .map(|n| n.to_string_lossy())
            .unwrap_or_default();
        let runner = match HookRunner::load_file(path) {
            Ok(r) => r,
            Err(e) => {
                tracing::warn!("hook '{name}' load error: {e}");
                continue;
            }
        };
        let input = build_hook_note_input(&current);
        let result = match runner.run(&input) {
            Ok(r) => r,
            Err(e) => {
                tracing::warn!("hook '{name}' run error: {e}");
                continue;
            }
        };
        match apply_hook_result(&result, &current) {
            Ok(out) => current = out,
            Err(e) => tracing::warn!("hook '{name}' apply error: {e}"),
        }
    }
    current
}

/// Compute the TextEdit needed to update `checklist-status` in a TOML metadata
/// block to `new_status`. Returns None if not found or already correct.
pub fn compute_toml_status_edit(content: &str, new_status: &str) -> Option<TextEdit> {
    let block = parser::find_toml_metadata_block(content)?;
    let lines: Vec<&str> = content.lines().collect();

    for i in block.start_line..=block.end_line {
        let line = lines.get(i)?;
        if line.trim_start().starts_with("checklist-status") {
            let new_line = format!("  checklist-status = \"{new_status}\"");
            if *line == new_line {
                return None;
            }
            return Some(TextEdit {
                range: Range {
                    start: Position {
                        line: i as u32,
                        character: 0,
                    },
                    end: Position {
                        line: i as u32,
                        character: line.len() as u32,
                    },
                },
                new_text: new_line,
            });
        }
    }
    None
}
